load("@rules_pkg//pkg:zip.bzl", "pkg_zip")

pkg_zip(
    name = "hello-world",
    srcs = [
        "@AMBEserver//:AMBEserver",
        "@APRSGateway//:APRSGateway",
        "@ircDDBGateway//:aprstransmitd",
        "@ircDDBGateway//:ircddbgatewayd",
        "@ircDDBGateway//:remotecontrold",
        "@ircDDBGateway//:starnetserverd",
        "@ircDDBGateway//:texttransmitd",
        "@ircDDBGateway//:timercontrold",
        "@ircDDBGateway//:timeserverd",
        "@ircDDBGateway//:voicetransmitd",
        "@DAPNETGateway//:DAPNETGateway",
        "@YSFClients//:DGIdGateway",
        "@YSFClients//:YSFGateway",
        "@YSFClients//:YSFParrot",
        "@MMDVM_CM//:DMR2NXDN",
        "@MMDVM_CM//:DMR2YSF",
        "@MMDVM_CM//:YSF2DMR",
        "@MMDVM_CM//:YSF2NXDN",
        "@MMDVM_CM//:YSF2P25",
        "@MMDVM_CM//:NXDN2DMR",
        "@DMRGateway//:DMRGateway",
        "@OpenDV//:dstarrepeaterdaemon",
        "@M17Gateway//:M17Gateway",
        "@MMDVMCal//:MMDVMCal",
        "@MMDVMHost//:MMDVMHost",
        "@MMDVMHost//:MMDVMHost_Adafruit",
        "@MMDVMHost//:RemoteCommand",
        "@WiringPi//:WiringPi",
        "@WiringPi//:WiringPiDev",
        "@NextionDriver//:NextionDriver",
        "@NXDNClients//:NXDNGateway",
        "@NXDNClients//:NXDNParrot",
        "@P25Clients//:P25Gateway",
        "@P25Clients//:P25Parrot",
        "@teensy_loader_cli//:teensy_loader_cli",
    ],
)
