load("@rules_sh//sh:sh.bzl", "sh_binaries")

sh_binaries(
    name = "wrappers",
    srcs = [
        "apt",
        "apt-get",
        "aptitude",
        "dpkg",
    ],
    visibility = ["//visibility:public"],
)
